package mx.gabvax.daog.model;

// Generated 5/04/2014 07:11:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Alumnos generated by hbm2java
 */
@Entity
@Table(name = "alumnos", catalog = "daos_genericos")
public class Alumnos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6745923001524005952L;
	private Integer idalumno;
	private Cursos cursos;
	private String nombre;
	private String direccion;
	private String grado;
	private String grupo;

	public Alumnos() {
	}

	public Alumnos(Cursos cursos, String nombre, String direccion,
			String grado, String grupo) {
		this.cursos = cursos;
		this.nombre = nombre;
		this.direccion = direccion;
		this.grado = grado;
		this.grupo = grupo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idalumno", unique = true, nullable = false)
	public Integer getIdalumno() {
		return this.idalumno;
	}

	public void setIdalumno(Integer idalumno) {
		this.idalumno = idalumno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcurso", nullable = false)
	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", nullable = false, length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "grado", nullable = false, length = 45)
	public String getGrado() {
		return this.grado;
	}

	public void setGrado(String grado) {
		this.grado = grado;
	}

	@Column(name = "grupo", nullable = false, length = 45)
	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

}
