package mx.gabvax.daog.model;

// Generated 5/04/2014 07:11:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cursos generated by hbm2java
 */
@Entity
@Table(name = "cursos", catalog = "daos_genericos")
public class Cursos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4265152078870959435L;
	private Integer idcurso;
	private String nombre;
	private Set<Alumnos> alumnoses = new HashSet<Alumnos>(0);

	public Cursos() {
	}

	public Cursos(String nombre) {
		this.nombre = nombre;
	}

	public Cursos(String nombre, Set<Alumnos> alumnoses) {
		this.nombre = nombre;
		this.alumnoses = alumnoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcurso", unique = true, nullable = false)
	public Integer getIdcurso() {
		return this.idcurso;
	}

	public void setIdcurso(Integer idcurso) {
		this.idcurso = idcurso;
	}

	@Column(name = "nombre", nullable = false, length = 45, columnDefinition = "LONGBLOB")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cursos")
	public Set<Alumnos> getAlumnoses() {
		return this.alumnoses;
	}

	public void setAlumnoses(Set<Alumnos> alumnoses) {
		this.alumnoses = alumnoses;
	}

}
